version: "3"

services:
  app:
    build:
      # For Dockerfile COPY
      context: ../
      dockerfile: ./dockerfiles/app/Dockerfile
    networks:
      - app
    ports:
      - 30001:30001

networks:
  app:
